---
name: "Frontastic Catwalk"
source: src
target: docs
autoloader: vendor/autoload.php
nameSpace: "\\Frontastic\\Catwalk"
files:
 - php/ApiCoreBundle/Domain/*.php
 - php/ApiCoreBundle/Domain/*/*.php
 - php/FrontendBundle/Domain/*.php
 - php/FrontendBundle/Domain/*/*.php
 - php/FrontendBundle/Routing/ObjectRouter/ProductRouter.php
reference:
 - ../../libraries/common/src/php/*ApiBundle/Domain/*.php
 - ../../libraries/common/src/php/*ApiBundle/Domain/*/*.php
 - ../../libraries/common/src/php/*ApiBundle/Domain/*/*/*.php
