imports:
    - { resource: config_dev.yml }

swiftmailer:
    # Providing null via environment variables does not work
    encryption: null

doctrine:
    dbal:
        dbname:     "%env(database_name)%_test"

services:
    # In our test environment we do not want a real logger
    logger:
        class: \Psr\Log\NullLogger
        public: true
