security:
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        assests:
            pattern: ^/(_(profiler|wdt)|assets)/
            security: false

        main:
            anonymous: ~
