openapi: 3.0.0
info:
  title: 'Frontastic Catwalk'
  version: 1.0.0
paths:
  //example.com/beforeGetCategories:
    post:
      summary: 'Before Decorator for getCategories'
      description: "Adapt the categories query before the query is executed against the\nbackend. If nothing is returned the original arguments will be used.\nThe URL and method can actually be configured by you."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                oneOf:
                  -
                    type: object
                    properties:
                      _type:
                        type: string
                        pattern: ^\Frontastic\Common\ProductApiBundle\Domain\ProductApi\Query\CategoryQuery$
                      parentId:
                        type: string
                      slug:
                        type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  oneOf:
                    -
                      type: object
                      properties:
                        _type:
                          type: string
                          pattern: ^\Frontastic\Common\ProductApiBundle\Domain\ProductApi\Query\CategoryQuery$
                        parentId:
                          type: string
                        slug:
                          type: string
                nullable: true
  //example.com/afterGetCategories:
    post:
      summary: 'After Decorator for getCategories'
      description: "Adapt the categories result. If nothing is returned the original result\nwill be used. The URL and method can actually be configured by you."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  _type:
                    type: string
                    pattern: ^\Frontastic\Common\ProductApiBundle\Domain\Category$
                  categoryId:
                    type: string
                  name:
                    type: string
                  depth:
                    type: integer
                  path:
                    type: string
                  slug:
                    type: string
                  dangerousInnerCategory: {  }
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    _type:
                      type: string
                      pattern: ^\Frontastic\Common\ProductApiBundle\Domain\Category$
                    categoryId:
                      type: string
                    name:
                      type: string
                    depth:
                      type: integer
                    path:
                      type: string
                    slug:
                      type: string
                    dangerousInnerCategory: {  }
                nullable: true
  //example.com/beforeQuery:
    post:
      summary: 'Before Decorator for query'
      description: "Adapt the product query before the query is executed against the\nbackend. If nothing is returned the original arguments will be used.\nThe URL and method can actually be configured by you."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                oneOf:
                  -
                    type: object
                    properties:
                      _type:
                        type: string
                        pattern: ^\Frontastic\Common\ProductApiBundle\Domain\ProductApi\Query\ProductQuery$
                      category:
                        type: string
                        nullable: true
                      sku:
                        type: string
                        nullable: true
                      skus:
                        type: array
                        items:
                          type: string
                        nullable: true
                      productId:
                        type: string
                        nullable: true
                      productIds:
                        type: array
                        items:
                          type: string
                        nullable: true
                      productType:
                        type: string
                        nullable: true
                      query:
                        type: string
                        nullable: true
                      filter:
                        type: array
                        items:
                          type: object
                          properties:
                            _type:
                              type: string
                              pattern: ^\Frontastic\Common\ProductApiBundle\Domain\ProductApi\Query\Filter$
                            handle:
                              type: string
                            attributeType:
                              type: string
                              nullable: true
                      facets:
                        type: array
                        items:
                          type: object
                          properties:
                            _type:
                              type: string
                              pattern: ^\Frontastic\Common\ProductApiBundle\Domain\ProductApi\Query\Facet$
                            handle:
                              type: string
                      sortAttributes:
                        type: array
                        items:
                          type: string
                      fuzzy:
                        type: boolean
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  oneOf:
                    -
                      type: object
                      properties:
                        _type:
                          type: string
                          pattern: ^\Frontastic\Common\ProductApiBundle\Domain\ProductApi\Query\ProductQuery$
                        category:
                          type: string
                          nullable: true
                        sku:
                          type: string
                          nullable: true
                        skus:
                          type: array
                          items:
                            type: string
                          nullable: true
                        productId:
                          type: string
                          nullable: true
                        productIds:
                          type: array
                          items:
                            type: string
                          nullable: true
                        productType:
                          type: string
                          nullable: true
                        query:
                          type: string
                          nullable: true
                        filter:
                          type: array
                          items:
                            type: object
                            properties:
                              _type:
                                type: string
                                pattern: ^\Frontastic\Common\ProductApiBundle\Domain\ProductApi\Query\Filter$
                              handle:
                                type: string
                              attributeType:
                                type: string
                                nullable: true
                        facets:
                          type: array
                          items:
                            type: object
                            properties:
                              _type:
                                type: string
                                pattern: ^\Frontastic\Common\ProductApiBundle\Domain\ProductApi\Query\Facet$
                              handle:
                                type: string
                        sortAttributes:
                          type: array
                          items:
                            type: string
                        fuzzy:
                          type: boolean
                nullable: true
  //example.com/afterQuery:
    post:
      summary: 'After Decorator for query'
      description: "Adapt the product query result. If nothing is returned the original\nresult will be used. The URL and method can actually be configured by\nyou."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                _type:
                  type: string
                  pattern: ^\Frontastic\Common\ProductApiBundle\Domain\ProductApi\Result$
                offset:
                  type: integer
                total:
                  type: integer
                count:
                  type: integer
                items:
                  type: array
                  items:
                    type: object
                    properties:
                      _type:
                        type: string
                        pattern: ^\Frontastic\Common\ProductApiBundle\Domain\Product$
                      productId:
                        type: string
                      changed:
                        type: string
                        nullable: true
                      version:
                        type: string
                        nullable: true
                      name:
                        type: string
                      slug:
                        type: string
                      description:
                        type: string
                      categories:
                        type: array
                        items:
                          type: string
                      variants:
                        type: array
                        items:
                          type: object
                          properties:
                            _type:
                              type: string
                              pattern: ^\Frontastic\Common\ProductApiBundle\Domain\Variant$
                            id:
                              type: string
                            sku:
                              type: string
                            groupId:
                              type: string
                            price:
                              type: integer
                            discountedPrice:
                              type: integer
                              nullable: true
                            discounts: {  }
                            currency:
                              type: string
                            attributes:
                              type: array
                              items: {  }
                            images:
                              type: array
                              items: {  }
                            isOnStock:
                              type: boolean
                            dangerousInnerVariant: {  }
                      dangerousInnerProduct: {  }
                facets:
                  type: array
                  items:
                    type: object
                    properties:
                      _type:
                        type: string
                        pattern: ^\Frontastic\Common\ProductApiBundle\Domain\ProductApi\Result\Facet$
                      type:
                        type: string
                      handle:
                        type: string
                      key:
                        type: string
                      selected:
                        type: boolean
                query:
                  type: object
                  properties:
                    _type:
                      type: string
                      pattern: ^\Frontastic\Common\ProductApiBundle\Domain\ProductApi\Query$
                    locale:
                      type: string
                    loadDangerousInnerData:
                      type: boolean
              nullable: true
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  _type:
                    type: string
                    pattern: ^\Frontastic\Common\ProductApiBundle\Domain\ProductApi\Result$
                  offset:
                    type: integer
                  total:
                    type: integer
                  count:
                    type: integer
                  items:
                    type: array
                    items:
                      type: object
                      properties:
                        _type:
                          type: string
                          pattern: ^\Frontastic\Common\ProductApiBundle\Domain\Product$
                        productId:
                          type: string
                        changed:
                          type: string
                          nullable: true
                        version:
                          type: string
                          nullable: true
                        name:
                          type: string
                        slug:
                          type: string
                        description:
                          type: string
                        categories:
                          type: array
                          items:
                            type: string
                        variants:
                          type: array
                          items:
                            type: object
                            properties:
                              _type:
                                type: string
                                pattern: ^\Frontastic\Common\ProductApiBundle\Domain\Variant$
                              id:
                                type: string
                              sku:
                                type: string
                              groupId:
                                type: string
                              price:
                                type: integer
                              discountedPrice:
                                type: integer
                                nullable: true
                              discounts: {  }
                              currency:
                                type: string
                              attributes:
                                type: array
                                items: {  }
                              images:
                                type: array
                                items: {  }
                              isOnStock:
                                type: boolean
                              dangerousInnerVariant: {  }
                        dangerousInnerProduct: {  }
                  facets:
                    type: array
                    items:
                      type: object
                      properties:
                        _type:
                          type: string
                          pattern: ^\Frontastic\Common\ProductApiBundle\Domain\ProductApi\Result\Facet$
                        type:
                          type: string
                        handle:
                          type: string
                        key:
                          type: string
                        selected:
                          type: boolean
                  query:
                    type: object
                    properties:
                      _type:
                        type: string
                        pattern: ^\Frontastic\Common\ProductApiBundle\Domain\ProductApi\Query$
                      locale:
                        type: string
                      loadDangerousInnerData:
                        type: boolean
                nullable: true
